# Generated by Django 5.0.7 on 2024-10-14 11:21

import django.db.models.deletion
import users.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('role', models.CharField(blank=True, choices=[('artist', 'Artist'), ('client', 'Client'), ('admin', 'Admin')], default='client', max_length=20, null=True)),
                ('joined', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('category', models.CharField(choices=[('bar_owner', 'Bar Owner'), ('regular', 'Regular'), ('event_organizer', 'Event Organizer')], default='regular', max_length=50)),
                ('is_roled', models.BooleanField(default=False)),
                ('production_page', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('doc_image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('doc_image3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('doc_image4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('doc_image5', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('business_permit', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('government_id', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('government_id_type', models.CharField(blank=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images/profiles/')),
                ('dob', models.DateField(blank=True, null=True, validators=[users.validators.date_not_future])),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, default='philippines', max_length=255, null=True)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('municipality', models.CharField(blank=True, max_length=255, null=True)),
                ('brgy', models.CharField(blank=True, max_length=60, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('fb_page', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(default='filipino', max_length=50)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
