# Generated by Django 5.0.7 on 2024-11-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_useraccount_is_suspended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
