# Generated by Django 5.0.7 on 2024-07-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_useraccount_profile_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.CharField(blank=True, choices=[('artist', 'Artist'), ('client', 'Client'), ('admin', 'Admin')], default='client', max_length=20, null=True),
        ),
    ]
