# Generated by Django 5.0.7 on 2024-11-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_useraccount_is_deactivated'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='warnings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
