# Generated by Django 5.0.7 on 2024-11-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_useraccount_warnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_chat_support',
            field=models.BooleanField(default=False),
        ),
    ]
