# Generated by Django 5.0.7 on 2024-08-01 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_useraccount_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='postal_code',
            new_name='zipcode',
        ),
    ]
