# Generated by Django 5.0.7 on 2024-11-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_useraccount_is_chat_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='government_id_back',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
