# Generated by Django 5.0.7 on 2024-08-14 09:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_clientprofile_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='profile_image'),
        ),
    ]
