# Generated by Django 5.0.7 on 2024-08-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_city_profile_municipality_profile_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default='philippines', max_length=255, null=True),
        ),
    ]
