# Generated by Django 5.0.7 on 2024-08-31 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='profile_image',
        ),
    ]
