# Generated by Django 5.0.7 on 2024-09-01 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_useraccount_created_useraccount_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='created',
            new_name='joined',
        ),
    ]
