# Generated by Django 5.0.7 on 2024-09-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_profile_language_profile_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_bar_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_event_organizer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_individual',
            field=models.BooleanField(default=False),
        ),
    ]
