# Generated by Django 5.0.7 on 2024-09-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_useraccount_is_bar_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_page', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('doc_image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('doc_image3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('doc_image4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('doc_image5', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('business_permit', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('government_id', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('government_id_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
