# Generated by Django 5.0.7 on 2024-09-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_roled',
            field=models.BooleanField(default=False),
        ),
    ]
