# Generated by Django 5.0.7 on 2024-09-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_profile_is_roled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_roled',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_roled',
            field=models.BooleanField(default=False),
        ),
    ]
