# Generated by Django 5.0.7 on 2024-09-25 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_profile_is_roled_useraccount_is_roled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_individual',
            new_name='is_regular',
        ),
    ]
