# Generated by Django 5.0.7 on 2024-09-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_rename_is_individual_useraccount_is_regular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_bar_owner',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_event_organizer',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_regular',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='category',
            field=models.CharField(choices=[('bar_owner', 'Bar Owner'), ('regular', 'Regular'), ('event_organizer', 'Event Organizer')], default='regular'),
        ),
    ]
