# Generated by Django 5.0.7 on 2024-09-26 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_useraccount_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
