# Generated by Django 5.0.7 on 2024-09-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_profile_business_permit_profile_doc_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='business_permit',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='doc_image1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='doc_image2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='doc_image3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='doc_image4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='doc_image5',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='government_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='government_id_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='production_page',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='business_permit',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='doc_image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='doc_image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='doc_image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='doc_image4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='doc_image5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='government_id',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='government_id_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='production_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
