# Generated by Django 5.0.7 on 2024-10-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_remove_profile_business_permit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelOptions(
            name='useraccount',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
