# Generated by Django 5.0.7 on 2024-09-19 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='transaction_id',
            new_name='reference_id',
        ),
    ]
