# Generated by Django 5.0.7 on 2024-10-11 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='artist',
        ),
        migrations.DeleteModel(
            name='DownPayment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Payout',
        ),
    ]
