# Generated by Django 5.0.7 on 2024-10-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_transaction_id_payment_reference_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='app_commission',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='payout',
            name='app_commission',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
