# Generated by Django 5.0.7 on 2024-10-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downpayment',
            name='payment_statys',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
