# Generated by Django 5.0.7 on 2024-10-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_downpayment_payment_statys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downpayment',
            old_name='payment_statys',
            new_name='payment_status',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='payout',
            name='payment_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
