# Generated by Django 5.0.7 on 2024-10-31 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0008_artist_account_holder_name_and_more'),
        ('booking', '0010_booking_venue'),
        ('payment', '0004_payment_refund_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payout_date', models.DateTimeField(auto_now_add=True)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_id', models.CharField(max_length=255)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='artists.artist')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.booking')),
            ],
        ),
    ]
