# Generated by Django 5.0.7 on 2024-11-13 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_payout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payer_name',
            new_name='payer_channel',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_gateway',
            new_name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='platform_fee',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='service_fee',
        ),
    ]
