# Generated by Django 5.0.7 on 2024-10-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_downpayment_payer_email_downpayment_payer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downpayment',
            name='payment_intent_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_intent_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='payment_intent_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
