# Generated by Django 5.0.7 on 2024-11-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_rename_payer_name_payment_payer_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='net_amount',
            field=models.IntegerField(),
        ),
    ]
