# Generated by Django 5.0.7 on 2024-11-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_payment_amount_alter_payment_net_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
