# Generated by Django 5.0.7 on 2024-11-14 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_payment_payer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payer',
            new_name='user',
        ),
    ]
