# Generated by Django 5.0.7 on 2024-11-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_rename_payer_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
