# Generated by Django 5.0.7 on 2024-11-21 07:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_payment_processing_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='echoease_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
