# Generated by Django 5.0.7 on 2024-10-20 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['is_read', '-created_at']},
        ),
    ]
