# Generated by Django 5.0.7 on 2024-10-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('message', 'Message'), ('new_booking', 'New Booking'), ('new_follower', 'New Follower'), ('booking_confirmation', 'Booking Confirmation'), ('booking_rejected', 'Booking Rejected'), ('payment_reminder', 'Payment Reminder'), ('event_reminder', 'Event Reminder'), ('downpayment_paid', 'Down Payment Paid')], max_length=50),
        ),
    ]
