# Generated by Django 5.0.7 on 2024-09-23 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_notification_artist_alter_notification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='artist',
        ),
    ]
