# Generated by Django 5.0.7 on 2024-11-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_rejected', 'Booking Rejected'), ('booking_confirmation', 'Booking Confirmation'), ('new_booking', 'New Booking'), ('downpayment_paid', 'Down Payment Paid'), ('dibursement_received', 'Dibursement Received'), ('refund_received', 'Refund Received'), ('message', 'Message'), ('new_follower', 'New Follower'), ('connection_request_accepted', 'Connection Request Accepted'), ('connection_request_rejected', 'Connection Request Rejected'), ('connection_request_sent', 'Connection Request Sent'), ('payment_reminder', 'Payment Reminder'), ('event_reminder', 'Event Reminder'), ('application_accepted', 'Application Accepted'), ('admin', 'Admin')], max_length=50),
        ),
    ]
