# Generated by Django 5.0.7 on 2024-08-01 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='users',
            new_name='parcitipants',
        ),
    ]
