# Generated by Django 5.0.7 on 2024-10-15 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('notification', '0002_alter_notification_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
