# Generated by Django 5.0.7 on 2024-10-15 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_reference',
        ),
    ]
