# Generated by Django 5.0.7 on 2024-11-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_conversation_blocked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='mark_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
