# Generated by Django 5.0.7 on 2024-10-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payer_email',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
