# Generated by Django 5.0.7 on 2024-11-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_transaction_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
