# Generated by Django 5.0.7 on 2024-10-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
