# Generated by Django 5.0.7 on 2024-09-05 01:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0028_artist_award_image1_artist_award_image2_and_more'),
        ('booking', '0002_alter_booking_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('artist', 'event_date', 'client')},
        ),
    ]
