# Generated by Django 5.0.7 on 2024-10-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_decline_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
