# Generated by Django 5.0.7 on 2024-10-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('artist', 'Artist')], null=True),
        ),
    ]
