# Generated by Django 5.0.7 on 2024-09-22 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0043_remove_artist_rate'),
        ('booking', '0006_booking_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artists.rate'),
        ),
    ]
