# Generated by Django 5.0.7 on 2024-10-20 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_has_sent_reminder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='has_sent_reminder',
            new_name='has_sent_payment_reminder',
        ),
    ]
