# Generated by Django 5.0.7 on 2024-10-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_rename_has_sent_reminder_booking_has_sent_payment_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
