# Generated by Django 5.0.7 on 2024-09-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_barangay_booking_landmark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='event_location',
        ),
    ]
