# Generated by Django 5.0.7 on 2024-10-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='venue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
