# Generated by Django 5.0.7 on 2024-11-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_booking_artist_alter_booking_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
