# Generated by Django 5.0.7 on 2024-09-23 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_remove_booking_duration_in_hours_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
    ]
