# Generated by Django 5.0.7 on 2024-10-09 02:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_alter_booking_options_alter_booking_artist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='event_time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
