# Generated by Django 5.0.7 on 2024-10-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_rename_event_time_booking_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='booking',
            name='has_downpayment',
            field=models.BooleanField(default=False),
        ),
    ]
