# Generated by Django 5.0.7 on 2024-11-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_alter_booking_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
