# Generated by Django 5.0.7 on 2024-10-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_alter_booking_options_booking_has_downpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='downpayment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
