# Generated by Django 5.0.7 on 2024-10-09 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_booking_downpayment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='downpayment_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='has_downpayment',
        ),
    ]
