# Generated by Django 5.0.7 on 2024-10-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_remove_booking_downpayment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
