# Generated by Django 5.0.7 on 2024-09-15 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0030_artist_bio'),
        ('booking', '0003_alter_booking_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disputant_type', models.CharField(choices=[('client', 'Client'), ('artist', 'Artist')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='under_review', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('performance_quality', 'Performance Quality'), ('cancellation', 'Cancellation'), ('no_show', 'No Show'), ('miscommunication', 'Miscommunication'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('date_resolved', models.DateField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='booking.booking')),
                ('disputant_artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispute_as_artist', to='artists.artist')),
                ('disputant_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispute_as_client', to=settings.AUTH_USER_MODEL)),
                ('respondent_artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispute_against_artist', to='artists.artist')),
                ('respondent_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispute_against_client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
