# Generated by Django 5.0.7 on 2024-09-18 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispute', '0002_artistdispute_clientdispute_delete_dispute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdispute',
            name='booking',
        ),
        migrations.DeleteModel(
            name='ArtistDispute',
        ),
        migrations.DeleteModel(
            name='ClientDispute',
        ),
    ]
