# Generated by Django 5.0.7 on 2024-10-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispute', '0004_dispute_client_alter_dispute_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputeevidence',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
