# Generated by Django 5.0.7 on 2024-10-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispute', '0005_alter_disputeevidence_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='reason',
            field=models.CharField(choices=[('performance_quality', 'Performance Quality'), ('cancellation', 'Cancellation'), ('no_show', 'No Show'), ('miscommunication', 'Miscommunication'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
