# Generated by Django 5.0.7 on 2024-11-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispute', '0007_alter_dispute_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='resolutioni',
            field=models.TextField(blank=True, null=True),
        ),
    ]
