# Generated by Django 5.0.7 on 2024-11-20 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispute', '0008_dispute_resolutioni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispute',
            old_name='resolutioni',
            new_name='resolution',
        ),
    ]
