# Generated by Django 5.0.7 on 2024-11-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispute', '0009_rename_resolutioni_dispute_resolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='reason',
            field=models.CharField(choices=[('performance_quality', 'Performance Quality'), ('cancellation', 'Cancellation'), ('no_show', 'No Show'), ('miscommunication', 'Miscommunication'), ('delayed_payment', 'Delayed Payment'), ('accomodation', 'Accomodation'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
