# Generated by Django 5.0.7 on 2024-11-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionlogs',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transactionlogs',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='transactionlogs',
            name='user',
        ),
        migrations.AddField(
            model_name='transactionlogs',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionlogs',
            name='transaction_type',
            field=models.CharField(max_length=60),
        ),
    ]
