# Generated by Django 5.0.7 on 2024-11-19 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_booking_latitude_booking_longitude'),
        ('logs', '0002_remove_transactionlogs_amount_and_more'),
        ('payment', '0013_remove_payment_refund_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlogs',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
        ),
        migrations.AddField(
            model_name='transactionlogs',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.payment'),
        ),
    ]
