# Generated by Django 5.0.7 on 2024-10-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='stage_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='stage_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
