# Generated by Django 5.0.7 on 2024-10-10 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unavailabledate',
            name='is_made',
        ),
    ]
