# Generated by Django 5.0.7 on 2024-10-21 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artist_stage_name_artistapplication_stage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessBoost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=255)),
                ('page_id', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_boost', to='artists.artist')),
            ],
        ),
    ]
