# Generated by Django 5.0.7 on 2024-10-13 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_remove_unavailabledate_is_made'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnavailableDate',
        ),
    ]
