# Generated by Django 5.0.7 on 2024-08-08 01:22

import artists.validators
import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_artistapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='artist',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='brgy',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='cover_photo',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='cover_photo'),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='dob',
            field=models.DateField(blank=True, null=True, validators=[artists.validators.date_not_future]),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='fb_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='fb_profile_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='profile_image'),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='sample_video1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='sample_video'),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='sample_video2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='sample_video'),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='sample_video3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='sample_video'),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='artistapplication',
            name='user',
            field=models.OneToOneField(default='under_review', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True, validators=[artists.validators.date_not_future])),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('brgy', models.CharField(blank=True, max_length=60, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('profile_image', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='profile_image')),
                ('cover_photo', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='cover_photo')),
                ('fb_page', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('fb_profile_link', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
