# Generated by Django 5.0.7 on 2024-10-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_businessboost'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='business_boost_opted',
            field=models.BooleanField(default=False),
        ),
    ]
