# Generated by Django 5.0.7 on 2024-08-08 02:15

import artists.validators
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_alter_artistapplication_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistapplication',
            name='brgy',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='artistapplication',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='artistapplication',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='artistapplication',
            name='dob',
            field=models.DateField(validators=[artists.validators.date_not_future]),
        ),
        migrations.AlterField(
            model_name='artistapplication',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='artistapplication',
            name='sample_video1',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='sample_video'),
        ),
        migrations.AlterField(
            model_name='artistapplication',
            name='street',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='artistapplication',
            name='zipcode',
            field=models.CharField(max_length=10),
        ),
    ]
