# Generated by Django 5.0.7 on 2024-10-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_artist_created_at_artist_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='date_approved',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='time_approved',
        ),
    ]
