# Generated by Django 5.0.7 on 2024-10-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0007_remove_artist_date_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='encrypted_account_number',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
