# Generated by Django 5.0.7 on 2024-10-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0008_artist_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='encrypted_account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
