# Generated by Django 5.0.7 on 2024-08-11 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0008_remove_artistapplication_cover_photo_artist_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='stage_name',
        ),
    ]
