# Generated by Django 5.0.7 on 2024-10-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0009_alter_artist_encrypted_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='encrypted_account_number',
            field=models.BinaryField(blank=True, max_length=255, null=True),
        ),
    ]
