# Generated by Django 5.0.7 on 2024-08-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0009_remove_artist_stage_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistapplication',
            old_name='profile_image',
            new_name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='profile_image',
        ),
    ]
