# Generated by Django 5.0.7 on 2024-11-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0010_alter_artist_encrypted_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='channel_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='channel_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='encrypted_account_number',
            field=models.BinaryField(blank=True, max_length=255, null=True),
        ),
    ]
