# Generated by Django 5.0.7 on 2024-08-16 01:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0010_rename_profile_image_artistapplication_cover_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistapplication',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='artist_profile_pic'),
        ),
        migrations.AlterField(
            model_name='artistapplication',
            name='cover_photo',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='cover_photo'),
        ),
    ]
