# Generated by Django 5.0.7 on 2024-11-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0011_artist_channel_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistapplication',
            name='encrypted_account_number',
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
