# Generated by Django 5.0.7 on 2024-08-16 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0012_artist_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='artistapplication',
            name='profile_pic',
        ),
    ]
