# Generated by Django 5.0.7 on 2024-11-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0012_remove_artistapplication_encrypted_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
