# Generated by Django 5.0.7 on 2024-11-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0013_artist_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
