# Generated by Django 5.0.7 on 2024-08-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0013_remove_artist_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='echo_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
