# Generated by Django 5.0.7 on 2024-08-29 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0014_artist_echo_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='echo_link',
        ),
    ]
