# Generated by Django 5.0.7 on 2024-08-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0015_remove_artist_echo_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='artists.genre'),
        ),
    ]
