# Generated by Django 5.0.7 on 2024-08-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0017_alter_artistapplication_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.ManyToManyField(blank=True, to='artists.genre'),
        ),
    ]
