# Generated by Django 5.0.7 on 2024-08-30 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0018_artist_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='brgy',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='city',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='country',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='street',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='zipcode',
        ),
        migrations.RemoveField(
            model_name='artistapplication',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='artistapplication',
            name='brgy',
        ),
        migrations.RemoveField(
            model_name='artistapplication',
            name='city',
        ),
        migrations.RemoveField(
            model_name='artistapplication',
            name='country',
        ),
        migrations.RemoveField(
            model_name='artistapplication',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='artistapplication',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='artistapplication',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='artistapplication',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='artistapplication',
            name='street',
        ),
        migrations.RemoveField(
            model_name='artistapplication',
            name='zipcode',
        ),
    ]
