# Generated by Django 5.0.7 on 2024-08-30 13:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0019_remove_artist_bio_remove_artist_brgy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistapplication',
            name='sample_video1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='sample_video'),
        ),
    ]
