# Generated by Django 5.0.7 on 2024-08-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0020_alter_artistapplication_sample_video1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
