# Generated by Django 5.0.7 on 2024-08-30 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0021_alter_genre_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistapplication',
            old_name='genre',
            new_name='genres',
        ),
    ]
