# Generated by Django 5.0.7 on 2024-09-01 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0023_alter_artistapplication_sample_video1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='fb_page',
            new_name='fb_link',
        ),
        migrations.RenameField(
            model_name='artistapplication',
            old_name='fb_page',
            new_name='fb_link',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='fb_profile_link',
        ),
        migrations.RemoveField(
            model_name='artistapplication',
            name='fb_profile_link',
        ),
    ]
