# Generated by Django 5.0.7 on 2024-09-01 16:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0025_rename_genre_artist_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='date_approved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='time_approved',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
