# Generated by Django 5.0.7 on 2024-09-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0026_artist_date_approved_artist_time_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='idol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='spotify',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='years_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='youtube',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='idol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='spotify',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='years_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='youtube',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
