# Generated by Django 5.0.7 on 2024-09-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0027_artist_idol_artist_spotify_artist_years_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='award_image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/awards'),
        ),
        migrations.AddField(
            model_name='artist',
            name='award_image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/awards'),
        ),
        migrations.AddField(
            model_name='artist',
            name='award_image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/awards'),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='award_image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/awards'),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='award_image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/awards'),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='award_image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/awards'),
        ),
    ]
