# Generated by Django 5.0.7 on 2024-09-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0028_artist_award_image1_artist_award_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistapplication',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
