# Generated by Django 5.0.7 on 2024-09-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0029_artistapplication_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
