# Generated by Django 5.0.7 on 2024-09-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0030_artist_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='file_type',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('image', 'Image'), ('document', 'Document')], max_length=50, null=True),
        ),
    ]
