# Generated by Django 5.0.7 on 2024-09-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0032_remove_portfolioitem_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='group',
            field=models.CharField(blank=True, choices=[('portfolio', 'Portfolio'), ('event', 'Event')], default='portfolio', max_length=50, null=True),
        ),
    ]
