# Generated by Django 5.0.7 on 2024-09-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0034_artist_back_id_artist_front_id_artist_id_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='back_id',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='front_id',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='id_type',
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='back_id',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='front_id',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='id_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
