# Generated by Django 5.0.7 on 2024-09-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0039_artistapplication_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='video1',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='video2',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
