# Generated by Django 5.0.7 on 2024-09-22 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0042_remove_artistapplication_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='rate',
        ),
    ]
