# Generated by Django 5.0.7 on 2024-09-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0043_remove_artist_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='connections',
            field=models.ManyToManyField(blank=True, to='artists.artist'),
        ),
    ]
