# Generated by Django 5.0.7 on 2024-10-05 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0047_alter_timeslot_end_time_alter_timeslot_start_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('artist', 'start_time', 'end_time')},
        ),
        migrations.CreateModel(
            name='TimeSlotException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.timeslot')),
            ],
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='is_booked',
        ),
    ]
