# Generated by Django 5.0.7 on 2024-10-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0050_alter_specialtimeslot_options_alter_timeslot_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitemmedia',
            name='file',
            field=models.FileField(upload_to='portfolio_item_medias/'),
        ),
    ]
