# Generated by Django 5.0.7 on 2024-10-06 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0051_alter_portfolioitemmedia_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='artists.portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
