# Generated by Django 5.0.7 on 2024-10-09 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0053_rate_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeSlot',
            new_name='DefaultTimeSlot',
        ),
        migrations.RenameModel(
            old_name='TimeSlotException',
            new_name='DefaultTimeSlotException',
        ),
    ]
