# Generated by Django 5.0.7 on 2024-10-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0054_rename_timeslot_defaulttimeslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaulttimeslotexception',
            name='full_day_exception',
            field=models.BooleanField(default=False),
        ),
    ]
