# Generated by Django 5.0.7 on 2024-10-10 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0056_unavailabledate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaulttimeslotexception',
            name='full_day_exception',
        ),
    ]
