# Generated by Django 5.0.7 on 2024-10-10 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0057_remove_defaulttimeslotexception_full_day_exception'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='defaulttimeslotexception',
            unique_together={('time_slot', 'date')},
        ),
    ]
