# Generated by Django 5.0.7 on 2024-10-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0058_alter_defaulttimeslotexception_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='unavailabledate',
            name='is_made',
            field=models.BooleanField(default=False),
        ),
    ]
